[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.redis", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.zip", "php82Extensions.curl", "php82Extensions.fileinfo", "php82Extensions.openssl", "php82Extensions.intl", "php82Extensions.bcmath", "php82Extensions.exif", "php82Extensions.ctype", "php82Extensions.tokenizer", "nginx", "nodejs", "php82Packages.composer"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci",
    "npm run production",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan event:cache"
]

[start]
cmd = "/app/start.sh"
